import { Task, Subject, Exam } from '../types';

export const mockSubjects: Subject[] = [
  { id: '1', name: 'Web Development', color: '#6366f1', teacher: 'Dr. Smith', taskCount: 5, credits: 4 },
  { id: '2', name: 'Database Systems', color: '#10b981', teacher: 'Prof. Johnson', taskCount: 3, credits: 3 },
  { id: '3', name: 'Data Structures', color: '#f59e0b', teacher: 'Dr. Williams', taskCount: 7, credits: 4 },
  { id: '4', name: 'Software Engineering', color: '#ef4444', teacher: 'Prof. Davis', taskCount: 4, credits: 3 },
  { id: '5', name: 'Operating Systems', color: '#8b5cf6', teacher: 'Dr. Miller', taskCount: 2, credits: 3 },
  { id: '6', name: 'Linear Algebra', color: '#06b6d4', teacher: 'Prof. Wilson', taskCount: 6, credits: 3 },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Complete React CRUD app',
    description: 'Build a task manager with full CRUD functionality using React hooks.',
    subject: 'Web Development',
    priority: 'high',
    status: 'in-progress',
    dueDate: '2026-04-15',
    createdAt: '2026-04-10',
  },
  {
    id: '2',
    title: 'SQL query optimization homework',
    description: 'Optimize the given queries using indexes and proper joins.',
    subject: 'Database Systems',
    priority: 'medium',
    status: 'todo',
    dueDate: '2026-04-17',
    createdAt: '2026-04-11',
  },
  {
    id: '3',
    title: 'Binary tree implementation',
    description: 'Implement BST with insert, delete, and traversal methods.',
    subject: 'Data Structures',
    priority: 'high',
    status: 'todo',
    dueDate: '2026-04-14',
    createdAt: '2026-04-09',
  },
  {
    id: '4',
    title: 'UML diagrams for project',
    description: 'Create class and sequence diagrams for the semester project.',
    subject: 'Software Engineering',
    priority: 'medium',
    status: 'done',
    dueDate: '2026-04-12',
    createdAt: '2026-04-08',
  },
  {
    id: '5',
    title: 'Memory management exercises',
    description: 'Complete exercises on paging, segmentation, and virtual memory.',
    subject: 'Operating Systems',
    priority: 'low',
    status: 'todo',
    dueDate: '2026-04-20',
    createdAt: '2026-04-11',
  },
  {
    id: '6',
    title: 'Matrix transformations problem set',
    description: 'Solve problems on eigenvalues, eigenvectors, and linear transformations.',
    subject: 'Linear Algebra',
    priority: 'high',
    status: 'in-progress',
    dueDate: '2026-04-16',
    createdAt: '2026-04-10',
  },
  {
    id: '7',
    title: 'REST API design document',
    description: 'Document all API endpoints for the semester project.',
    subject: 'Web Development',
    priority: 'medium',
    status: 'done',
    dueDate: '2026-04-11',
    createdAt: '2026-04-07',
  },
];

export const mockExams: Exam[] = [
  {
    id: '1',
    title: 'Midterm Exam',
    subject: 'Web Development',
    subjectColor: '#6366f1',
    date: 'April 20, 2026',
    topics: ['React', 'Node.js', 'REST APIs'],
    room: 'Room 301',
  },
  {
    id: '2',
    title: 'Final Exam',
    subject: 'Database Systems',
    subjectColor: '#10b981',
    date: 'May 5, 2026',
    topics: ['SQL', 'Normalization', 'Indexes'],
    room: 'Lab 102',
  },
  {
    id: '3',
    title: 'Quiz 3',
    subject: 'Data Structures',
    subjectColor: '#f59e0b',
    date: 'April 18, 2026',
    topics: ['Trees', 'Graphs', 'Sorting'],
    room: 'Room 205',
  },
  {
    id: '4',
    title: 'Project Review',
    subject: 'Software Engineering',
    subjectColor: '#ef4444',
    date: 'April 25, 2026',
    topics: ['SCRUM', 'Design Patterns', 'Testing'],
    room: 'Auditorium A',
  },
];
